pipeline {
  agent any

  stages {
    stage ('git clone') {
      steps {
        git branch: 'main', changelog: false, poll: false, url: 'https://github.com/Cloud-Lucky/microservices-app.git'
      }
    }
    stage ('docker build') {
      steps {
        dir('user-service') {
          sh 'docker build -t user-service:1.0 .
        }
      }
    }
  }
}
